### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by elinorgodzilla** [myselfshravan/AI-Meal-Planner#1]
Hi!
I keep getting the "anthropic.AuthenticationError" 
Despite the error I am grateful for this helpful app, looking forward to try it once you can sort this out!

**Comment by myselfshravan** [comment]
@elinorgodzilla I have changed the API key and everything seems perfect now. Could you give it a try and let me know if it's working. Thank you

**Comment by elinorgodzilla** [comment]
Works perfectly now, thank you! I am so happy I found this project, it's really great and useful, creative implementation of claude.

**Comment by elinorgodzilla** [comment]
Hi! same error again, can you please change API key again?

**Comment by myselfshravan** [comment]
> Hi! same error again, can you please change API key again?

Anthropic gave a notice on high volume of prompts coming from my keys that violate therefore they have revoked the access to it.
