### ISSUE TITLE
Cannot use it

### ISSUE THREAD

**Issue by hallo1126** [myselfshravan/AI-Meal-Planner#2]
I cannot use this program. It says it needs a key... I would really like to use it.

**Comment by myselfshravan** [comment]
could you check now

**Comment by AnkitTripathi1609** [comment]
I want to deploy it from my end , what all keys it needed and what all changes to do for same?

**Comment by myselfshravan** [comment]
you will need to add api key into the folder .streamlit/secrets.toml
